#!/usr/bin/env python3
"""Build the public config example from widget-owned settings declarations."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
WIDGETS = ROOT / "widgets" / "src" / "widgets"
LAUNCHER_SETTINGS = ROOT / "widgets" / "src" / "launcher" / "settings.json"
OUTPUT = ROOT / "config.example.json"
COMMENT = (
    "Generated by tools/config-example.py from each widget's settings.json. "
    "Copy to config.json (git-ignored) or ~/.config/opscope/config.json. "
    "Every key is optional; anything omitted keeps the widget's default."
)


def render() -> str:
    config: dict[str, object] = {"_comment": COMMENT}
    config["terminal"] = json.loads(LAUNCHER_SETTINGS.read_text())
    for settings in sorted(WIDGETS.glob("*/settings.json")):
        section = settings.parent.name.replace("-", "_")
        body = json.loads(settings.read_text())
        body.pop("_schema", None)
        config[section] = body
    return json.dumps(config, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when config.example.json is not the generated result",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != generated:
            print("config.example.json is stale; run tools/config-example.py")
            return 1
        return 0
    OUTPUT.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
